<?php
define("CONTROLLERS_PATH","Application/controllers");
define("VIEWS_PATH","Application/views");
define("MODELS_PATH","Application/models");
define("DB_HOST","localhost");
define("DB_NAME","test");
define("DB_USERNAME","root");
define("DB_PASSWORD","");
define("SITE_URL","http://127.0.0.1/Stock");
define("CSS_PATH",SITE_URL."/public/css");
define("JS_PATH",SITE_URL."/public/js");
define("IMG_PATH",SITE_URL."/public/img");
define("PLUGINS_PATH",SITE_URL."/public/plugins");